
```{r}
library(tidyverse)
data=read.csv("data.csv",stringsAsFactors = TRUE)
data$is_canceled=as.factor(data$is_canceled)
```

```{r}
#Hotel Bookings Cancellation vs Non Cancellation Count
ggplot(data=data,mapping=aes(x=is_canceled,fill=is_canceled))+geom_bar()+ggtitle("Hotel Bookings: Canceled vs Not Canceled")+ylab("Count")+
  scale_x_discrete(labels = c("0" = "Not Canceled", "1" = "Canceled"))+xlab("Cancellation")+
  scale_fill_manual(values = c("0" = "#002845", "1" = "#841F27"),labels=c("Not Canceled","Canceled")) +
  guides(fill=guide_legend(title="Cancellation Status"))+ theme(plot.background = element_rect(fill = "#002845"),axis.text=element_text(color = "white"),axis.title = element_text(color = "white"),plot.title=element_text(face = "bold",color = "white"))
```

```{r}
#Historical Cancellation Status by Market Segment
ggplot(data,mapping=aes(x=market_segment,fill=is_canceled))+geom_bar(position="dodge")+ ggtitle("Historical Cancellation Status by Market Segment") + xlab("Market Segment")+ ylab("Count") +
  scale_fill_manual(values = c("0" = "#002845", "1" = "#841F27"),labels=c("Not Canceled","Canceled")) +
  guides(fill=guide_legend(title="Cancellation Status"))+ theme(plot.background = element_rect(fill = "#002845"),axis.text.x = element_text(angle = 45, hjust = 1),axis.text=element_text(color = "white"),axis.title = element_text(color = "white"),plot.title=element_text(face = "bold",color = "white"))
```

```{r}

data_req= data %>% group_by(deposit_type, is_canceled) %>%
  summarise(count = n(),.groups = "drop") %>%
  group_by(deposit_type) %>%
  mutate(percentage = count / sum(count) * 100)


ggplot(data = data_req, mapping = aes(x = deposit_type, y = count, fill = is_canceled)) +
  geom_bar(stat = "identity", position = "dodge") +
  xlab("Deposit Type") + 
  ylab("Count") +
  labs(fill = "Cancellation Status") +
  ggtitle("Cancellation Status by Deposit Type") +
  scale_fill_manual(
    values = c("0" = "#002845", "1" = "#841F27"),
    labels = c("Not Canceled", "Canceled")
  ) +
  guides(fill = guide_legend(title = "Cancellation Status")) +
  theme(
    plot.background = element_rect(fill = "#002845"),
    axis.text = element_text(color = "white"),
    axis.title = element_text(color = "white"),
    plot.title = element_text(face = "bold", color = "white")
  ) +
  geom_text(
    aes(label = paste0(round(percentage), "%"),y = count + 2000),
    position = position_dodge(width = 0.9),
    color = "black",
    size = 3
  )

#Historical Cancellation Status by Lead Time Bins.
data$lead_timeCategories=factor(data$lead_timeCategories,levels=c("Very Low Lead Time","Below Average Lead Time","Above Average Lead Time","High Lead Time"))
ggplot(data,mapping=aes(x=lead_timeCategories,fill=is_canceled))+geom_bar(position="dodge")+ ggtitle("Historical Cancellation Status by Lead Time Bins") + xlab("Lead Time Bins")+ ylab("Count") +
  scale_fill_manual(values = c("0" = "#002845", "1" = "#841F27"),labels=c("Not Canceled","Canceled")) +
  guides(fill=guide_legend(title="Cancellation Status"))+ theme(axis.text.x = element_text(angle = 45, hjust = 1),plot.background = element_rect(fill = "#002845"),axis.text=element_text(color = "white"),axis.title = element_text(color = "white"),plot.title=element_text(face = "bold",color = "white"))
```



```{r}
data_req= data %>% group_by(lead_timeCategories, is_canceled) %>%
  summarise(count = n(),.groups = "drop") %>%
  group_by(lead_timeCategories) %>%
  mutate(percentage = count / sum(count) * 100)


ggplot(data = data_req, mapping = aes(x = lead_timeCategories, y = count, fill = is_canceled)) +
  geom_bar(stat = "identity", position = "dodge") +
  xlab("Lead Time Bins") + 
  ylab("Count") +
  labs(fill = "Cancellation Status") +
  ggtitle("Cancellation Status by Lead Time") +
  scale_fill_manual(
    values = c("0" = "#002845", "1" = "#841F27"),
    labels = c("Not Canceled", "Canceled")
  ) +
  guides(fill = guide_legend(title = "Cancellation Status")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
    plot.background = element_rect(fill = "#002845"),
    axis.text = element_text(color = "white"),
    axis.title = element_text(color = "white"),
    plot.title = element_text(face = "bold", color = "white")
  ) +
  geom_text(
    aes(label = paste0(round(percentage), "%"),y = count + 1000),
    position = position_dodge(width = 0.9),
    color = "black",
    size = 3
  )
```


```{r}
#Historical Cancellation Status by Lead Time Bins.
data$lead_timeCategories=factor(data$lead_timeCategories,levels=c("Very Low Lead Time","Below Average Lead Time","Above Average Lead Time","High Lead Time"))
ggplot(data,mapping=aes(x=lead_timeCategories,fill=is_canceled))+geom_bar(position="dodge")+ ggtitle("Historical Cancellation Status by Lead Time") + xlab("Lead Time Bins")+ ylab("Count") +
  scale_fill_manual(values = c("0" = "#002845", "1" = "#841F27"),labels=c("Not Canceled","Canceled")) +
  guides(fill=guide_legend(title="Cancellation Status"))+ theme(axis.text.x = element_text(angle = 45, hjust = 1),plot.background = element_rect(fill = "#002845"),axis.text=element_text(color = "white"),axis.title = element_text(color = "white"),plot.title=element_text(face = "bold",color = "white"))
```

```{r}
ggplot(data=data,mapping=aes(x=required_car_parking_spaces,fill=is_canceled))+geom_bar(position="dodge")+ xlab("Required Parking Spaces")+ ylab("Count") +
labs(fill = "Cancellation Status")+ ggtitle("Cancelation Status by Required Parking Spaces")+
  scale_fill_manual(values = c("0" = "#002845", "1" = "#841F27"),labels=c("Not Canceled","Canceled")) +
  guides(fill=guide_legend(title="Cancellation Status"))+ theme(plot.background = element_rect(fill = "#002845"),axis.text=element_text(color = "white"),axis.title = element_text(color = "white"),plot.title=element_text(face = "bold",color = "white")) +coord_cartesian(xlim=c(-0.5,2))
```


```{r}

ggplot(data=data,mapping=aes(x=assigned_room_type,fill=is_canceled))+geom_bar(position="dodge")+ xlab("Room Type")+ ylab("Count") + ggtitle("Cancelation Status by Room Type")+
  scale_fill_manual(values = c("0" = "#002845", "1" = "#841F27"),labels=c("Not Canceled","Canceled")) +
  guides(fill=guide_legend(title="Cancellation Status"))+ theme(plot.background = element_rect(fill = "#002845"),axis.text=element_text(color = "white"),axis.title = element_text(color = "white"),plot.title=element_text(face = "bold",color = "white"))
```



```{r}
company204=data[data$company==204,]
ggplot(data=company204,mapping=aes(x=company,fill=is_canceled))+geom_bar(position="dodge")+ xlab("Company")+ ylab("Count") + ggtitle("Cancelation Status of Company 204")+
  scale_fill_manual(values = c("0" = "#002845", "1" = "#841F27"),labels=c("Not Canceled","Canceled")) +
  guides(fill=guide_legend(title="Cancellation Status"))+ theme(plot.background = element_rect(fill = "#002845"),axis.text=element_text(color = "white"),axis.title = element_text(color = "white"),plot.title=element_text(face = "bold",color = "white"))
```

```{r}
company321=data[data$company==321,]
ggplot(data=company321,mapping=aes(x=company,fill=is_canceled))+geom_bar(position="dodge")+ xlab("Company")+ ylab("Count") + ggtitle("Cancellation Status of Company 321")+
  scale_fill_manual(values = c("0" = "#002845", "1" = "#841F27"),labels=c("Not Canceled","Canceled")) +
  guides(fill=guide_legend(title="Cancellation Status"))+ theme(plot.background = element_rect(fill = "#002845"),axis.text=element_text(color = "white"),axis.title = element_text(color = "white"),plot.title=element_text(face = "bold",color = "white"))

```

```{r}
roomtypeI=data[data$assigned_room_type=="I",]
ggplot(data=roomtypeI,mapping=aes(x=assigned_room_type,fill=is_canceled))+geom_bar(position="dodge")+ xlab("Room Type")+ ylab("Count") + ggtitle("Cancellation Status of Room Type I")+
  scale_fill_manual(values = c("0" = "#002845", "1" = "#841F27"),labels=c("Not Canceled","Canceled")) +
  guides(fill=guide_legend(title="Cancellation Status"))+ theme(plot.background = element_rect(fill = "#002845"),axis.text=element_text(color = "white"),axis.title = element_text(color = "white"),plot.title=element_text(face = "bold",color = "white"))

```

```{r}
ggplot(data=data,mapping=aes(x=previous_cancellations,fill=is_canceled))+geom_bar(position="dodge")+ xlab("Previous Cancellations")+ ylab("Count")+ ggtitle("Cancellation Status by Number of Previous Cancellations")+
  scale_fill_manual(values = c("0" = "#002845", "1" = "#841F27"),labels=c("Not Canceled","Canceled")) +
  guides(fill=guide_legend(title="Cancellation Status"))+ theme(plot.background = element_rect(fill = "#002845"),axis.text=element_text(color = "white"),axis.title = element_text(color = "white"),plot.title=element_text(face = "bold",color = "white"))+coord_cartesian(xlim=c(-0.5,2))
```

```{r}
data_req= data %>% group_by(total_of_special_requests, is_canceled) %>%
  summarise(count = n(),.groups = "drop") %>%
  group_by(total_of_special_requests) %>%
  mutate(percentage = count / sum(count) * 100)


ggplot(data = data_req, mapping = aes(x = total_of_special_requests, y = count, fill = is_canceled)) +
  geom_bar(stat = "identity", position = "dodge") +
  xlab("Number of Special Requests") + 
  ylab("Count") +
  labs(fill = "Cancellation Status") +
  ggtitle("Cancellation Status by Amount of Special Requests") +
  scale_fill_manual(
    values = c("0" = "#002845", "1" = "#841F27"),
    labels = c("Not Canceled", "Canceled")
  ) +
  guides(fill = guide_legend(title = "Cancellation Status")) +
  theme(
    plot.background = element_rect(fill = "#002845"),
    axis.text = element_text(color = "white"),
    axis.title = element_text(color = "white"),
    plot.title = element_text(face = "bold", color = "white")
  ) +
  geom_text(
    aes(label = paste0(round(percentage), "%"),y = count + 1000),
    position = position_dodge(width = 0.9),
    color = "black",
    size = 3
  )
```


```{r}
ggplot(data=data,mapping=aes(x=total_of_special_requests,fill=is_canceled))+geom_bar(position="dodge")+ xlab("Total of Special Requests")+ ylab("Count") +
  scale_fill_manual(values = c("0" = "#002845", "1" = "#841F27"),labels=c("Not Canceled","Canceled")) +ggtitle("Cancellations by Total of Special Requests")+
  guides(fill=guide_legend(title="Cancellation Status"))+ theme(plot.background = element_rect(fill = "#002845"),axis.text=element_text(color = "white"),axis.title = element_text(color = "white"),plot.title=element_text(face = "bold",color = "white"))
```

```{r}
ggplot(data=data,mapping=aes(x=meal,fill=is_canceled))+geom_bar(position="dodge")+ xlab("Meal")+ ylab("Count") +
labs(fill = "Cancellation Status")+ggtitle("Cancellation Status by Meal Type")+
  scale_fill_manual(values = c("0" = "#002845", "1" = "#841F27"),labels=c("Not Canceled","Canceled")) +
  guides(fill=guide_legend(title="Cancellation Status"))+ theme(plot.background = element_rect(fill = "#002845"),axis.text=element_text(color = "white"),axis.title = element_text(color = "white"),plot.title=element_text(face = "bold",color = "white"))
```


```{r}
ggplot(data=data,mapping=aes(x=customer_type,fill=is_canceled))+geom_bar(position="dodge")+ xlab("Customer Type")+ ylab("Count") + ggtitle("Cancellation Status by Customer Type")+
  scale_fill_manual(values = c("0" = "#002845", "1" = "#841F27"),labels=c("Not Canceled","Canceled")) +
  guides(fill=guide_legend(title="Cancellation Status"))+ theme(plot.background = element_rect(fill = "#002845"),axis.text=element_text(color = "white"),axis.title = element_text(color = "white"),plot.title=element_text(face = "bold",color = "white"))
```
```{r}
country=data%>%group_by(country)%>%summarize(total=n(),cancellation_rate=sum(is_canceled==1)/total,`Not Canceled`=sum(is_canceled==0),`Canceled` =sum(is_canceled==1))%>%filter(total > 500)%>%arrange(desc(cancellation_rate))%>%head(10)

ggplot(country, aes(x = reorder(country, -cancellation_rate), y = cancellation_rate)) +
  geom_col(fill = "#841F27") +
    ggtitle("Top 10 Countries by Cancellation Rate")+
    xlab("Country")+
    ylab("Cancellation Rate")+
  scale_y_continuous(labels = scales::percent,limits = c(0, 1)) + # Show y-axis as percentages
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+ theme(plot.background = element_rect(fill = "#002845"),axis.text=element_text(color = "white"),axis.title = element_text(color = "white"),plot.title=element_text(face = "bold",color = "white"))
```



```{r}
agent=data%>%group_by(agent)%>%summarize(total=n(),cancellation_rate=sum(is_canceled==1)/total,`Not Canceled`=sum(is_canceled==0),`Canceled` =sum(is_canceled==1))%>%filter(total >500)%>%arrange(desc(cancellation_rate))%>%head(10)

ggplot(agent, aes(x = reorder(agent, -cancellation_rate), y = cancellation_rate)) +
  geom_col(fill = "#841F27") +
    ggtitle("Top 10 Agent by Cancellation Rate")+
    xlab("Agent")+
    ylab("Cancellation Rate")+
  scale_y_continuous(labels = scales::percent,limits = c(0, 1)) +
 theme_minimal() +  theme(axis.text.x = element_text(angle = 45, hjust = 1))+theme(plot.background = element_rect(fill = "#002845"),axis.text=element_text(color = "white"),axis.title = element_text(color = "white"),plot.title=element_text(face = "bold",color = "white"))
```

```{r}
data_summary <- data %>%
  group_by(meal, is_canceled) %>%
  summarise(count = n(), .groups = "drop") %>%
  group_by(meal) %>%
  mutate(percentage = count / sum(count) * 100)

# Create the plot
library(ggplot2)

ggplot(data = data_summary, 
       mapping = aes(x = meal, y = count, fill = as.factor(is_canceled))) +
  geom_bar(stat = "identity", position = "dodge") +
  xlab("Meal") + 
  ylab("Count") +
  labs(fill = "Cancellation Status") +
  ggtitle("Cancellation Status by Meal Type") +
  scale_fill_manual(
    values = c("0" = "#002845", "1" = "#841F27"),
    labels = c("Not Canceled", "Canceled")
  ) +
  guides(fill = guide_legend(title = "Cancellation Status")) +
  theme(
    plot.background = element_rect(fill = "#002845"),
    axis.text = element_text(color = "white"),
    axis.title = element_text(color = "white"),
    plot.title = element_text(face = "bold", color = "white")
  ) +
  geom_text(
    aes(
      label = paste0(round(percentage, 1), "%"),
      y = count + 1000  # Adjust position above the bars
    ),
    position = position_dodge(width = 0.9),
    color = "black",
    size = 3
  )
```

